# Generated by Django 3.1.2 on 2020-10-19 02:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Costumer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('costumer_name', models.CharField(max_length=200)),
                ('costumer_email', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='CostumerPhoneNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=0)),
                ('type', models.CharField(blank=True, choices=[('c', 'cell-phone'), ('w', 'work-phone'), ('a', 'home-phone')], default='a', help_text='Phone types', max_length=1)),
                ('contact', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_confirmation', models.IntegerField(primary_key=True, serialize=False)),
                ('order_total', models.FloatField()),
                ('costumer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.costumer')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.IntegerField(unique=True)),
                ('cost', models.IntegerField(default=0)),
                ('description', models.CharField(max_length=200)),
                ('pushed_product', models.BooleanField()),
                ('callback', models.CharField(max_length=200)),
                ('category', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.category')),
            ],
        ),
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ProductInstance',
            fields=[
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='products.product')),
                ('inventory_on_hand', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('code', models.ForeignKey(db_column='code', on_delete=django.db.models.deletion.PROTECT, to='products.product', to_field='code')),
                ('order_confirmation', models.ForeignKey(db_column='order_confirmation', on_delete=django.db.models.deletion.PROTECT, to='products.order')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.producttype'),
        ),
        migrations.AddField(
            model_name='costumer',
            name='costumer_phone',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.costumerphonenumber'),
        ),
    ]
